local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.prod[:aws][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.prod[:aws][:secret_access_key] %>
  region: us-east-1
  bucket: <%= ENV['S3_BUCKET_NAME'] %>

amazon_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.dev[:aws][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.dev[:aws][:secret_access_key] %>
  region: eu-west-2
  bucket: dexters-lab